# Generated by Django 6.0.2 on 2026-03-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_article_content_html_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_html',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
